### ISSUE TITLE
an option to use pcre regex (disabling wildcard)

### ISSUE THREAD

**Issue by Cyrille37** [okapi-web/php-wildcards#3]
Hi,

Like talk in okapi-web/php-aop#31 would you agree to add an option to disable wildcard to use pcre regex?

Something like:
```php
public static function fromWildcard(string $wildcard, bool $pcre = false ): self
{
  if( $pcre )
  {
        $regex = str_replace('/', '\/', $wildcard);
  }
  else
  {
    // actual implementation
  }
  $regex = new self('/^'.$regex.'$/');
  $regex->wildcard = $wildcard;
  return $regex;
}
```

If you agree, I'll propose a pull request soon :-)

**Comment by WalterWoshid** [comment]
Hi @Cyrille37,

sorry for the late reply, had some health problems I needed to take care of first.

I'm sorry, but this would not be the point of this library, as PHP already supports regex and I want to keep code as clean as possible. Instead I would add it directly to the `MethodAdvice` class! Would be happy if you create a PR for `okapi-web/php-aop` directly :)
